source 'https://rubygems.org'
gem 'sinatra' #, '1.3.4'
gem 'sinatra-flash', '0.3.0', require: 'sinatra/flash'
gem 'bcrypt' #, '3.0.1'
gem 'data_mapper' #, '1.2.0'
gem 'dm-sqlite-adapter' #, '1.2.0'
gem 'warden' #, '1.2.3'
gem 'shotgun' # , '0.9.1'
gem 'rake'
gem 'minitest'
gem 'minitest-reporters'
gem 'rack-test', require: 'rack/test'
gem 'pact'